{% set name = "opentelemetry-exporter-otlp" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp-{{ version }}.tar.gz
  sha256: cafcf7f28debbcc22e06d52cdc4f65a118f17b730dabe8f9d4b87587e95b1481

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-exporter-otlp-proto-grpc ==1.18.0
    - opentelemetry-exporter-otlp-proto-http ==1.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.otlp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp
  summary: OpenTelemetry Collector Exporters
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
